#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Bundle-CPANPLUS-Dependencies
version:      0.01
version_from: lib/Bundle/CPANPLUS/Dependencies.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
